version: "3.8"

services:
  my_app:
    build: .
    volumes:
      - ./credentials:/app/credentials
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./app/credentials/credentials.json
